In [119]:
A = 1//1*[1 2; -8 -5; -1 0; 0 -1]
b = 1//1*[3, -10, 0, 0]

4-element Array{Rational{Int64},1}:
   3//1
 -10//1
   0//1
   0//1

In [120]:
∇f = x -> 2*x -[4, 4]

#9 (generic function with 1 method)

In [121]:
using JuMP

In [122]:
using Clp

In [172]:
function optimize_direction(X)
    
    m = Model(solver = ClpSolver()) 
    @variable(m,  d0)
    @variable(m,  d1)
    
    @constraint(m, -1 <= d0)
    @constraint(m, d0 <= 1)
    
    @constraint(m, -1 <= d1)
    @constraint(m, d1 <= 1)
        
    active = A*X .< b
    println("AX = ", A*X)
    for i in 1:4
        if ! active[i]
            println(i, " active")
            @constraint(m, A[i,1]*d0 + A[i,2]'*d1 <= 0)
        else
            println(i, " free")
            println((A*X)[i] , " <= ", b[i] )
        end
    end
            
    grad = ∇f(X)
    println("grad = ", grad)
    @objective(m, Min, grad[1]*d0 + grad[2]'*d1)
    solve(m)
    return m, [getvalue(d0), getvalue(d1)]
end

function optimize_α(X, d)
    x, y = X
    println("AX <= b", A*X .<= b)
    d0, d1 = d
    α = (-x*d0+2*d0-y*d1+2*d1)//(d0*d0+d1*d1)
    println("α_f = ", α)
    right = b-A*X
    mx = 100000000//1*ones(Int64, 4)
    for i in 1:length(mx)
        if b[i] - (A*X)[i]!= 0
            mx[i] =  (b[i] - A[i,:]'*X)/(A[i,:]'*d)
        end
        
        if 0 <= mx[i] < α 
            α = mx[i]
        end
    end
    println("mx = ",mx)
    return α
            
end

optimize_α (generic function with 1 method)

In [173]:
X0 = [3//2, 1//2]
println("X0 = ", X0)
m, d1 = optimize_direction(X0)
println("d1 = ", d1)
d1 = [1//1, 1//1]

α1 = optimize_α(X0, d1)

println("α1 = ", α1)
X1 = X0 + α1*d1
println(m)

X0 = Rational{Int64}[3//2, 1//2]
AX = Rational{Int64}[5//2, -29//2, -3//2, -1//2]
1 free
5//2 <= 3//1
2 free
-29//2 <= -10//1
3 free
-3//2 <= 0//1
4 free
-1//2 <= 0//1
grad = Rational{Int64}[-1//1, -3//1]
d1 = [1.0, 1.0]
AX <= bBool[true, true, true, true]
α_f = 1//1
mx = Rational{Int64}[1//6, -9//26, -3//2, -1//2]
α1 = 1//6
Min -d0 - 3 d1
Subject to
 -d0 ≤ 1
 d0 ≤ 1
 -d1 ≤ 1
 d1 ≤ 1
 d0
 d1



In [174]:
println("X1 = ", X1)
m, d2 = optimize_direction(X1)
println("d2 = ", d2)
d2 = [-1//1, 1//2]
α2 = optimize_α(X1, d2)
println("α2 = ", α2)
X2 = X1 + α2*d2

println(m)

X1 = Rational{Int64}[5//3, 2//3]
AX = Rational{Int64}[3//1, -50//3, -5//3, -2//3]
1 active
2 free
-50//3 <= -10//1
3 free
-5//3 <= 0//1
4 free
-2//3 <= 0//1
grad = Rational{Int64}[-2//3, -8//3]
d2 = [-1.0, 0.5]
AX <= bBool[true, true, true, true]
α_f = 4//15
mx = Rational{Int64}[100000000//1, 40//33, 5//3, -4//3]
α2 = 4//15
Min -0.6666666666666666 d0 - 2.6666666666666665 d1
Subject to
 -d0 ≤ 1
 d0 ≤ 1
 -d1 ≤ 1
 d1 ≤ 1
 d0 + 2 d1 ≤ 0
 d0
 d1



In [175]:
println("X2 = ", X2)
m, d3 = optimize_direction(X2)
d3 = [-1//1, 1//2]
println("d = ", d3)
α3 = optimize_α(X2, d3)
println("α3 = ", α3)
X3 = X2 + α3*d3

X2 = Rational{Int64}[7//5, 4//5]
AX = Rational{Int64}[3//1, -76//5, -7//5, -4//5]
1 active
2 free
-76//5 <= -10//1
3 free
-7//5 <= 0//1
4 free
-4//5 <= 0//1
grad = Rational{Int64}[-6//5, -12//5]
d = Rational{Int64}[-1//1, 1//2]
AX <= bBool[true, true, true, true]
α_f = 0//1
mx = Rational{Int64}[100000000//1, 52//55, 7//5, -8//5]
α3 = 0//1


2-element Array{Rational{Int64},1}:
 7//5
 4//5

In [178]:
m

Minimization problem with:
 * 5 linear constraints
 * 2 variables
Solver is Clp

In [179]:
Rational{Int64}[-6//5, -12//5]'*d3

0//1

# Numero 3

In [180]:
M = [1 0 0 0; 0.4 0 0.6 0; 0.2 0 0.1 0.7; 0 0 0 1]

4×4 Array{Float64,2}:
 1.0  0.0  0.0  0.0
 0.4  0.0  0.6  0.0
 0.2  0.0  0.1  0.7
 0.0  0.0  0.0  1.0

In [181]:
using LinearAlgebra

In [195]:
A = Array{Float64, 2}(I,4, 4)
B = Array{Float64, 2}(I,4, 4)
B*=M

4×4 Array{Float64,2}:
 1.0  0.0  0.0  0.0
 0.4  0.0  0.6  0.0
 0.2  0.0  0.1  0.7
 0.0  0.0  0.0  1.0

In [210]:
A = Array{Float64, 2}(I,4, 4)
B = Array{Float64, 2}(I,4, 4)
B*=M
expr = 0
while norm(A - B) > 1e-8
    A[:,:] = B[:,:]
    B *= M
    println("\$P^", expr, "\$")
    to_tex(A)
    expr+=1
end
expr

$P^0$
\\[begin{pmatrix}
1.0 & 0.0 & 0.0 & 0.0 & \\
0.4 & 0.0 & 0.6 & 0.0 & \\
0.2 & 0.0 & 0.1 & 0.7 & \\
0.0 & 0.0 & 0.0 & 1.0 & \\
\end{pmatrix}\]$P^1$
\\[begin{pmatrix}
1.0 & 0.0 & 0.0 & 0.0 & \\
0.52 & 0.0 & 0.06 & 0.42 & \\
0.22 & 0.0 & 0.010000000000000002 & 0.7699999999999999 & \\
0.0 & 0.0 & 0.0 & 1.0 & \\
\end{pmatrix}\]$P^2$
\\[begin{pmatrix}
1.0 & 0.0 & 0.0 & 0.0 & \\
0.532 & 0.0 & 0.006 & 0.46199999999999997 & \\
0.222 & 0.0 & 0.0010000000000000002 & 0.7769999999999999 & \\
0.0 & 0.0 & 0.0 & 1.0 & \\
\end{pmatrix}\]$P^3$
\\[begin{pmatrix}
1.0 & 0.0 & 0.0 & 0.0 & \\
0.5332 & 0.0 & 0.0006000000000000001 & 0.46619999999999995 & \\
0.2222 & 0.0 & 0.00010000000000000003 & 0.7777 & \\
0.0 & 0.0 & 0.0 & 1.0 & \\
\end{pmatrix}\]$P^4$
\\[begin{pmatrix}
1.0 & 0.0 & 0.0 & 0.0 & \\
0.53332 & 0.0 & 6.000000000000001e-5 & 0.4666199999999999 & \\
0.22222 & 0.0 & 1.0000000000000004e-5 & 0.77777 & \\
0.0 & 0.0 & 0.0 & 1.0 & \\
\end{pmatrix}\]$P^5$
\\[begin{pmatrix}
1.0 & 0.0 & 0.0 & 0.0 & \\

9

In [208]:
[1.0 0.0 0.0 0.0; 0.533332 0.0 6.0e-6 0.466662; 0.222222 0.0 1.0e-6 0.777777; 0.0 0.0 0.0 1.0]

4×4 Array{Float64,2}:
 1.0       0.0  0.0     0.0     
 0.533332  0.0  6.0e-6  0.466662
 0.222222  0.0  1.0e-6  0.777777
 0.0       0.0  0.0     1.0     

In [209]:
function to_tex(m::Matrix)
    println("\\\\[begin{pmatrix}")
    for i in 1:size(m, 1)
        for j in 1:size(m, 2)
            print(m[i,j], " & ")
        end
        println("\\\\")
    end
    print("\\end{pmatrix}\\]")
end

to_tex (generic function with 1 method)

In [206]:
to_tex(ones(2,2))

\begin{pmatrix}
1.0 & 1.0 & \\
1.0 & 1.0 & \\
\end{pmatrix}

In [213]:
M^1000

4×4 Array{Float64,2}:
 1.0       0.0  0.0  0.0     
 0.533333  0.0  0.0  0.466667
 0.222222  0.0  0.0  0.777778
 0.0       0.0  0.0  1.0     

In [217]:
convert(Rational, 0.53333333333333333333333333333333333333333333333)

4803839602528529//9007199254740992

In [226]:
8/15

0.5333333333333333

In [228]:
2/9

0.2222222222222222

In [231]:
O = [1 0 0 0; 8//15 0 0 7//15; 2//9 0 0 7//9; 0 0 0 1]

4×4 Array{Rational{Int64},2}:
 1//1   0//1  0//1  0//1 
 8//15  0//1  0//1  7//15
 2//9   0//1  0//1  7//9 
 0//1   0//1  0//1  1//1 

In [365]:
V = 1//10*[3 5 2; 0 3 7; 0 0 10]
sol = [0,0,1//1]

3-element Array{Rational{Int64},1}:
 0//1
 0//1
 1//1

In [358]:
V'*sol

3-element Array{Rational{Int64},1}:
 0//1
 0//1
 1//1

In [361]:
A = 1/10*[8 2 0;3 5 2; 0 3 7]

3×3 Array{Float64,2}:
 0.8  0.2  0.0
 0.3  0.5  0.2
 0.0  0.3  0.7

In [364]:
A^100

3×3 Array{Float64,2}:
 0.473684  0.315789  0.210526
 0.473684  0.315789  0.210526
 0.473684  0.315789  0.210526

In [ ]:
A